[build]
	publish = "_site"
	command = "bun run build"

[build.environment]
	NODE_VERSION = "18"
	NPM_FLAGS = "--production=false"

# Redirect subdomain blog.otherdev.com to main site if needed
# [[redirects]]
#   from = "/*"
#   to = "https://otherdev.com/blog/:splat"
#   status = 301
#   condition = "host:blog.otherdev.com"

# Headers for performance and security
[[headers]]
	for = "/*"
	[headers.values]
		X-Frame-Options = "DENY"
		X-XSS-Protection = "1; mode=block"
		X-Content-Type-Options = "nosniff"
		Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
	for = "/css/*"
	[headers.values]
		Cache-Control = "public, max-age=31536000"

[[headers]]
	for = "/img/*"
	[headers.values]
		Cache-Control = "public, max-age=31536000"

[[headers]]
	for = "/fonts/*"
	[headers.values]
		Cache-Control = "public, max-age=31536000"
